#!/bin/sh

# A simple wrapper around xrandr to work easily with external displays

IN="eDP1"
EXT="DP2"

# If no external display is connected, or if one is connected and enabled,
# toggle it off.
if (xrandr | grep "$EXT disconnected") || !(xrandr | grep "$EXT connected (normal left inverted right x axis y axis)"); then
    xrandr --output $IN --auto --output $EXT --off 
    exit
fi

if [ "$1" == "--right" ]; then
    DIR="right"
elif [ "$1" == "--left" ]; then
    DIR="left"
elif [ "$1" == "--off" ]; then
    xrandr --output $IN --auto --output $EXT --off; exit
else
    exit 1
fi


xrandr --output $IN --auto --primary --output $EXT --auto --$DIR-of $IN
sleep 1

# Reapply background image
feh --bg-scale ~/Pictures/iranshrine.jpg
