#!/bin/sh

# Locates window with "Youtube" in the title, moves mouse to center of that
# window, left-clicks, and restores mouse to initial position.
# Depends on xdotool (https://github.com/jordansissel/xdotool)

ID=$(xdotool search --limit 1 --onlyvisible --name "Youtube")

eval "$(xdotool getmouselocation --shell)"
INITX=$X
INITY=$Y
INITSCR=$SCREEN

# Sets variables: WINDOW X Y WIDTH HEIGHT SCREEN
eval "$(xdotool getwindowgeometry --shell "$ID")"

xdotool mousemove --window "$ID" $(("$WIDTH"/2)) $(("$HEIGHT"/2)) click 1 \
    mousemove --screen "$INITSCR" "$INITX" "$INITY"
