#!/bin/bash

# Sets up a Wacom tablet to my liking: left-handed, only pen/no touch,
# mapped only to my external display, buttons for undo/redo and zoom +/-

STY=$(xsetwacom --list devices | grep STYLUS | cut -f 2 | cut -d: -f2)
TOUCH=$(xsetwacom --list devices | grep TOUCH | cut -f 2 | cut -d: -f2)
PAD=$(xsetwacom --list devices | grep PAD | cut -f 2 | cut -d: -f2)
ERASE=$(xsetwacom --list devices | grep ERASER | cut -f 2 | cut -d: -f2)

## DEFAULTS ##

# Left handedness!
for i in $STY $TOUCH $ERASE; do xsetwacom --set $i Rotate half; done

# Touch pad off
for i in $STY $TOUCH $ERASE; do xsetwacom --set $i Touch off; done

# Map pen to external monitor (fails gracefully if no ext. monitor present)
for i in $STY; do xsetwacom --set $i MapToOutput "DP2"; done

# Undo, Redo
xsetwacom --set $PAD Button 3 " key +ctrl z -ctrl"
xsetwacom --set $PAD Button 8 " key +ctrl y -ctrl"

# Zoom in/out
xsetwacom --set $PAD Button 1 " key +ctrl +shift + -shift -ctrl"
xsetwacom --set $PAD Button 9 " key +ctrl - -ctrl"

for ARG in $@; do
    case $ARG in
        right)  
            for i in $STY $TOUCH $ERASE; do \
                xsetwacom --set $i Rotate none; done ;;
        touch)
            for i in $STY $TOUCH $ERASE; do \
                xsetwacom --set $i Touch on; done ;;

        youtube|yt)
            xsetwacom --set $PAD \
                Button 9 " key +super +shift y -shift -super" ;;
        touch-map)
            for i in $STY $TOUCH $ERASE; do \
                xsetwacom --set $i MapToOutput desktop; done
    esac
done
