theme = "native"
icons = "awesome5"

[[block]]
block = "custom"
command = "echo '[-]'"
interval = "once"
on_click = "~/bin/keyset && ~/bin/font-sizer-alacritty"

[[block]]
block = "cpu"
interval = 4

[[block]]
block = "load"
interval = 8
format = "{1m}|{5m}|{15m}"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
primary_only = true
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
interface_name_include = []

[[block]]
block = "backlight"
step_width = 1

[[block]]
block = "battery"
format = "{percentage}% {time} {power}W"
interval = 13

[[block]]
block = "sound"
on_click = "pavucontrol"
step_width = 2

[[block]]
block = "time"
interval = 30
format = "%a %m/%d %R"
